### ISSUE TITLE
访问网易云音乐api时出现问题

### ISSUE THREAD

**Issue by JunketPear** [JumpAlang/Jusic-Serve-Houses#14]
如题
当我在访问网易云的api的时候
出现了如下报错
![image](https://user-images.githubusercontent.com/58849532/163790599-1675e60b-4e93-4ca2-a357-354d87182639.png)
访问其他api页面都正常
![image](https://user-images.githubusercontent.com/58849532/163790645-5212a936-2c69-4c24-8711-4f9385626d59.png)
程序是使用docker一键部署
已将docker中的3000，3300，3400，8081映射至公网
求解答awa

**Comment by JumpAlang** [comment]
docker-compose.yml这个文件使用的音乐api版本是1.4？如下
 service_jusicMusicApi:
    image: jumpalang/jusic_music_api:1.4
    environment:

**Comment by JunketPear** [comment]
是的
![image](https://user-images.githubusercontent.com/58849532/164173018-9c2ad870-0af4-4dc7-a63b-391e2d21f9b2.png)

**Comment by JumpAlang** [comment]
我测试了我这边你正常的。你可以进入容器查看下日志

**Comment by JunketPear** [comment]
![image](https://user-images.githubusercontent.com/58849532/164217096-7bddc6a3-70fb-44a0-8424-e1b98930c62a.png)
如图

**Comment by JunketPear** [comment]
已经进行了删除重装 仍然报错如上

**Comment by JumpAlang** [comment]
有没有外网地址 可以测试

**Comment by JunketPear** [comment]
101.42.227.91:3000

**Comment by JunketPear** [comment]
所有服务都是默认端口

**Comment by JumpAlang** [comment]
我访问都是正常的啊，网易的歌也是正常的

**Comment by JunketPear** [comment]
就是您访问3000端口也是正常的是吗

**Comment by JunketPear** [comment]
好的 麻烦您了
