### ISSUE TITLE
大佬 网易云点歌docker logs老是报需要验证，是我还少了什么配置吗 通过你那个compose部署的

### ISSUE THREAD

**Issue by Thormaa** [JumpAlang/Jusic-Serve-Houses#26]
![image](https://user-images.githubusercontent.com/69197378/203920111-7f3f2840-7c80-4fd6-8e66-3a36d797328e.png)
![image](https://user-images.githubusercontent.com/69197378/203920234-3e9a130f-eaf2-465f-8db9-b1ea41191806.png)

**Comment by Thormaa** [comment]
好像昨晚还好好的 早上就突然这样了。。

**Comment by JumpAlang** [comment]
有登录网易帐号吗

**Comment by Thormaa** [comment]
想问下具体哪块配置是在做网易账号认证的呢还是怎么样 😄

**Comment by JumpAlang** [comment]
https://github.com/JumpAlang/Jusic-Serve-Houses/issues/4#issuecomment-766493294

**Comment by Thormaa** [comment]
thx
