### ISSUE TITLE
【feature request】是否可以支持新增暂停播放功能？

### ISSUE THREAD

**Issue by doveeeee** [JumpAlang/Jusic-Serve-Houses#27]
### 需求背景
我们是几个同事在一个房间一起听歌，早上点了一堆歌之后，到了午休时间去吃饭了，午休结束后发现点的歌全部播完了，需要重新点。这里可以加一个暂停功能，在午休时暂停。
另，作为一个播放器，添加暂停功能也蛮合理的~

### 可能的实现方式
- 在 `Music` model 中新增 `private long pauseTime` ，未暂停可置0，前端收到信息后根据 `pushTime` 计算暂停时间点来暂停歌曲。
- 在`House` model 中新增 `private Boolean pause` ，表示该房间听歌是否暂停

可以设置为只有管理员可以暂停，或者也可以设置投票暂停(感觉投票比较麻烦，管理员暂停比较方便)

当然也有很多场景没有详细考虑，代码也没详细看，甚至不知道放在哪里比较合适~ 这里仅提供一下我的浅薄思路

题外话：可否增加支持一键导入整个歌单功能~  我不知道是我没玩明白还是确实不支持，我想点一整个歌单，需要一首一首的点，感觉比较麻烦2333

**Comment by JumpAlang** [comment]
1. 关于暂停问题，今天有更新了个功能，单曲循环，这个应该能解决你的问题（目前还是不支持暂停功能，如果我是用户我进入房间想要听歌没有声音，总感觉奇怪）
2. 目前系统是支持一键导入网易或者qq的歌单，参照教程如下：
  > 设置默认播放列表（当点歌列表为空时，默认从此加载歌曲）：“ 设置默认列表 24381616,1” ，其中243881616和1是歌单id

**Comment by doveeeee** [comment]
感谢！
