### ISSUE TITLE
这个怎么删除已存在房间

### ISSUE THREAD

**Issue by xhazy01** [JumpAlang/Jusic-Serve-Houses#29]
如题，比如**默认房间**或者**永存的房间**

**Comment by JumpAlang** [comment]
* 默认房间无法删除，只能修改
* 调用api:http://ip:8080/house/edit
* Authorization 选择Basic auth
* body json传参：
``` json{
    "id":"OPOjUegQ",  //房间id
    "canDestroy":true //是否销毁
   
}
```
