### ISSUE TITLE
使用doker-compose部署 配置网易云会员账号之后 听会员音乐还是只有30秒

### ISSUE THREAD

**Issue by St-Yukio** [JumpAlang/Jusic-Serve-Houses#30]
![image](https://github.com/JumpAlang/Jusic-Serve-Houses/assets/42167342/357cbb08-54ea-4e6f-b727-087841aab7f2)

![image](https://github.com/JumpAlang/Jusic-Serve-Houses/assets/42167342/3f842c2b-1a33-415c-8fb7-00bde3513109)
![image](https://github.com/JumpAlang/Jusic-Serve-Houses/assets/42167342/ee2c2b83-ca3d-4a08-a2fe-b3beaa9def78)

**Comment by FranklinBao** [comment]
@St-Yukio 后来是怎么配置成功的？
